name: Validate-Markdown

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  validate-markdown:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      repository-projects: read
      pull-requests: write

    steps:
      # Step 1: Check out the source code of the pull request.
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - uses: articulate/actions-markdownlint@v1
        with:
          config: ./.markdownlint/config.json
